// =============================================================================
// homomorphic-esp32-ultrades.ino
//
// Homomorphic DES supervisor evaluation benchmark for the ESP32.
// Uses EC-ElGamal encryption (secp256k1) to evaluate supervisors without
// ever decrypting the state vector in the normal run path.
//
// ── QUICK START ──────────────────────────────────────────────────────────────
//  1. Run the UltraDES notebook → generates supervisor_data_<PROBLEM>.h
//  2. Copy the .h file to this sketch folder.
//  3. Update the #include below to match the filename.
//  4. Flash and open Serial Monitor at 115200 baud.
//
// ── DATA FORMAT ──────────────────────────────────────────────────────────────
// supervisor_data_<PROBLEM>.h contains direct C arrays in PROGMEM (flash).
// There is NO JSON, NO ArduinoJson, NO runtime parsing.
// All supervisor data is read with pgm_read_byte() / pgm_read_word().
//
// ── HOW IT WORKS ─────────────────────────────────────────────────────────────
// Each supervisor state is encrypted as an EC-ElGamal ciphertext.
// At each simulation step:
//   1. The encrypted state vector is updated via a sparse matrix transition
//      (ciphertext copies — no decryption needed).
//   2. Enablement is checked homomorphically: we compute Enc(Σ row·state)
//      and decrypt only the scalar result (0 or 1).
//   3. SHADOW OPTIMISATION: a cleartext copy of the state distribution is
//      kept in parallel. For one-hot states (always true in deterministic DES)
//      the enablement result can be read directly from flash — zero decryptions.
//      Decryption is only triggered when the shadow shows multiple active states.
//   4. The Oracle (pure cleartext) runs independently for correctness checking.
//
// ── MEMORY STRATEGY ──────────────────────────────────────────────────────────
// Ciphertexts are stored as COMPRESSED EC POINTS (33 bytes each = 66 bytes per
// ciphertext). Full mbedtls_ecp_point structs (~400 bytes) are only created
// transiently during arithmetic and freed immediately after. This lets us fit
// supervisors with 100+ states in the ESP32's 320 KB DRAM.
//
// ── OPTIMISATIONS ────────────────────────────────────────────────────────────
//  1. PROGMEM C arrays      — zero parse time, data read directly from flash
//  2. Compressed points     — 66 bytes/ciphertext vs ~400 with full structs
//  3. Shadow state          — skips HE decrypt for one-hot states (common case)
//  4. own_event_mask        — O(1) bitmask: does this supervisor own this event?
//  5. trans_event_mask      — O(1) bitmask: does this event move this supervisor?
//  6. constrained_gi list   — precomputed list of constraining event indices
//  7. secp256k1 curve       — a=0 allows faster point-addition formula in mbedTLS
//  8. yield() between ops   — lets RTOS reclaim heap between EC operations
//  9. Self-test on boot     — verifies crypto before any benchmark runs
//
// ── REQUIRED LIBRARIES ───────────────────────────────────────────────────────
// No external libraries needed — only the ESP32 Arduino core + mbedTLS.
// =============================================================================

#include <Arduino.h>
#include <esp_heap_caps.h>        // heap_caps_get_free_size() for memory reporting
#include <mbedtls/ecp.h>          // EC point arithmetic
#include <mbedtls/bignum.h>       // Multi-precision integers
#include <mbedtls/entropy.h>      // Hardware entropy source
#include <mbedtls/ctr_drbg.h>     // Deterministic random bit generator
#include <pgmspace.h>             // pgm_read_byte / pgm_read_word (PROGMEM access)
#include <vector>
#include <string>

// ── Change this to match the .h file generated by the notebook ───────────────
#include "supervisor_data_fms.h"


// =============================================================================
// SECTION 1 — CONFIGURATION
// =============================================================================

// secp256k1 (Bitcoin's curve) has a = 0, which enables a faster Jacobian
// point-addition formula inside mbedTLS (~15-25% faster than secp256r1).
#define CURVE MBEDTLS_ECP_DP_SECP256K1

// Compressed EC point: 1 prefix byte (0x02 or 0x03) + 32-byte X coordinate.
// Two per ciphertext = 66 bytes total.
// Full mbedtls_ecp_point structs would cost ~400 bytes per ciphertext — 6× more.
#define PT_LEN 33

// Set to 1 to force full HE decryption every step (benchmark mode).
// Set to 0 to enable the shadow optimisation (production mode).
// With FORCE_HE_DECRYPT 0, one-hot states skip decryption entirely —
// the timing will appear very fast but does not reflect HE cost.
// With FORCE_HE_DECRYPT 1, every constraining event triggers sum_row +
// elgamal_decrypt — this is the true homomorphic evaluation cost.
#define FORCE_HE_DECRYPT 1


// =============================================================================
// SECTION 2 — TYPES
// =============================================================================

// ── Ciphertext ────────────────────────────────────────────────────────────────
// Stores one EC-ElGamal ciphertext as two compressed points.
// Plain byte arrays — no heap allocation inside the struct.
// Arithmetic (sum_row, decrypt) decompresses into temporary ecp_point values
// and frees them immediately after.
struct Ciphertext {
    uint8_t c1[PT_LEN];   // r·G  (randomised component)
    uint8_t c2[PT_LEN];   // m·G + r·Pub  (message component)
};

// ── SupDesc ───────────────────────────────────────────────────────────────────
// Descriptor generated by the notebook and stored in the .h file.
// All pointer fields point into PROGMEM — read-only flash storage.
// (Defined in the generated .h file — shown here for documentation.)
//
// struct SupDesc {
//     const char*      name;       // supervisor label (PROGMEM)
//     uint16_t         num_states;
//     const int8_t*    init;       // one-hot initial state  [num_states]
//     const int8_t*    enable;     // enablement matrix      [EVENT_COUNT × num_states]
//     const uint16_t*  tcnt;       // transition pair counts [EVENT_COUNT]
//     const int16_t*   trans;      // flat (from,to) pairs
// };

// ── Supervisor (runtime) ──────────────────────────────────────────────────────
// Extends SupDesc with live encrypted state, bitmasks, and the shadow.
struct Supervisor {
    const SupDesc* desc;   // pointer to the PROGMEM descriptor

    // ── Bitmasks (built once at load time, O(1) lookup per step) ─────────────
    // bit i = 1 means this supervisor responds to / has transitions on event i.
    uint32_t own_event_mask    = 0;   // supervisor owns event i (enablement or transition)
    uint32_t trans_event_mask  = 0;   // supervisor has ≥1 transition on event i
    uint32_t constraining_mask = 0;   // supervisor has ≥1 disabled state for event i

    // Precomputed list of global event indices that are constraining.
    // Avoids re-scanning PROGMEM every step to find which events need checking.
    std::vector<uint8_t> constrained_gi;

    // ── Encrypted state ───────────────────────────────────────────────────────
    // enc[s] = EC-ElGamal encryption of the state indicator for state s.
    // For a one-hot state vector, exactly one enc[s] encrypts 1, rest encrypt 0.
    std::vector<Ciphertext> enc;

    // ── Enablement cache ──────────────────────────────────────────────────────
    // cached_en[li] = last computed enablement result for constraining event li.
    // Valid when cache_valid = true. Avoids redundant decryptions.
    std::vector<int8_t> cached_en;
    bool cache_valid = false;

    // ── Shadow state ──────────────────────────────────────────────────────────
    // Cleartext copy of the state distribution, updated via the SAME transitions
    // as enc[]. Never used for output — only used to skip HE decryption.
    //
    // For deterministic DES, the state is always one-hot: exactly one state
    // is active at a time. When shadow shows active_count == 1, the enablement
    // result is just a PROGMEM table lookup — no EC operations needed at all.
    // Only if active_count > 1 (should not happen in a valid supervisor) do
    // we fall back to the full HE decrypt path.
    std::vector<int8_t> shadow;
};


// =============================================================================
// SECTION 3 — GLOBALS
// =============================================================================

static std::vector<Supervisor> g_sups;   // loaded supervisors for current benchmark

// ── mbedTLS EC crypto context ─────────────────────────────────────────────────
static mbedtls_ecp_group        g_grp;      // curve parameters
static mbedtls_ecp_point        g_G;        // generator point
static mbedtls_ecp_point        g_pub;      // public key (Pub = priv·G)
static mbedtls_mpi              g_priv;     // private key scalar
static mbedtls_mpi              g_one;      // constant 1 (used in ecp_muladd)
static mbedtls_ctr_drbg_context g_drbg;    // random number generator
static mbedtls_entropy_context  g_entropy;  // hardware entropy source

// Enc(0) — used to fill "empty" slots in sparse transitions.
// Precomputed once and reused to avoid redundant encryptions.
static Ciphertext g_zero;

// EC operation timing (measured once on boot, used in timing estimates).
static long g_muladd_ms    = 0;    // time for one ecp_muladd call (ms)
static long g_scalarmul_ms = 80000; // time for one ecp_mul call (ms)

// Per-step counter of actual HE decryptions performed (vs shadow-skipped).
static int g_step_decrypts = 0;


// =============================================================================
// SECTION 4 — PROGMEM READ HELPERS
// =============================================================================
// Thin wrappers around pgm_read_byte / pgm_read_word for typed access.
// Using these instead of raw casts makes the code easier to read and avoids
// accidental alignment bugs on non-AVR platforms.

inline int8_t pm_i8(const int8_t* arr, int idx) {
    return (int8_t)pgm_read_byte(arr + idx);
}

inline int16_t pm_i16(const int16_t* arr, int idx) {
    return (int16_t)pgm_read_word(arr + idx);
}

inline uint16_t pm_u16(const uint16_t* arr, int idx) {
    return (uint16_t)pgm_read_word(arr + idx);
}

// Read the PROGMEM string pointer for event gi from the EVENT_NAMES table.
inline const char* pm_event_name(int gi) {
    return (const char*)pgm_read_ptr(&EVENT_NAMES[gi]);
}


// =============================================================================
// SECTION 5 — COMPRESSED POINT HELPERS
// =============================================================================
// EC points are stored in compressed form (33 bytes) and only expanded into
// full mbedtls_ecp_point structs during arithmetic.

// Compress a full EC point → 33-byte array.
inline int pt_compress(const mbedtls_ecp_point* P, uint8_t out[PT_LEN]) {
    size_t len = 0;
    return mbedtls_ecp_point_write_binary(
        &g_grp, P, MBEDTLS_ECP_PF_COMPRESSED, &len, out, PT_LEN);
}

// Decompress a 33-byte array → freshly initialised mbedtls_ecp_point.
// Caller MUST call mbedtls_ecp_point_free() when done.
inline int pt_decompress(const uint8_t in[PT_LEN], mbedtls_ecp_point* P) {
    mbedtls_ecp_point_init(P);
    return mbedtls_ecp_point_read_binary(&g_grp, P, in, PT_LEN);
}


// =============================================================================
// SECTION 6 — EC-ElGamal CRYPTO
// =============================================================================
//
// EC-ElGamal over secp256k1:
//   Key generation : priv ← random scalar;  Pub = priv·G
//   Encrypt(m)     : r ← random;  c1 = r·G;  c2 = m·G + r·Pub
//   Decrypt(c1,c2) : m·G = c2 - priv·c1;  m = (is_point_at_infinity ? 0 : 1)
//   Add(ct_a,ct_b) : (c1_a+c1_b, c2_a+c2_b)   — homomorphic addition mod G
//
// Plaintext domain is {0, 1} — sufficient for DES state indicators.
// Decryption distinguishes zero (point at infinity) from non-zero (any other point).

// Helper: R = P + Q using ecp_muladd(1·P + 1·Q).
static int ecp_add_pts(mbedtls_ecp_point* R,
                       const mbedtls_ecp_point* P,
                       const mbedtls_ecp_point* Q) {
    return mbedtls_ecp_muladd(&g_grp, R, &g_one, P, &g_one, Q);
}

// Encrypt m ∈ {0, 1} → compressed Ciphertext.
static int elgamal_encrypt(int m, Ciphertext* ct) {
    mbedtls_mpi r;
    mbedtls_ecp_point rP, c1_pt, c2_pt;
    mbedtls_mpi_init(&r);
    mbedtls_ecp_point_init(&rP);
    mbedtls_ecp_point_init(&c1_pt);
    mbedtls_ecp_point_init(&c2_pt);

    // c1 = r·G  (randomised component, binds the ciphertext to a random r)
    int ret = mbedtls_ecp_gen_privkey(&g_grp, &r, mbedtls_ctr_drbg_random, &g_drbg);
    if (ret) goto done;
    ret = mbedtls_ecp_mul(&g_grp, &c1_pt, &r, &g_G,
                           mbedtls_ctr_drbg_random, &g_drbg);
    if (ret) goto done;

    // rP = r·Pub  (shared secret component)
    ret = mbedtls_ecp_mul(&g_grp, &rP, &r, &g_pub,
                           mbedtls_ctr_drbg_random, &g_drbg);
    if (ret) goto done;

    if (m == 0) {
        // Enc(0): c2 = rP  (message component is the point at infinity masked by rP)
        mbedtls_ecp_copy(&c2_pt, &rP);
    } else {
        // Enc(m): c2 = m·G + rP  (embed m as a scalar multiple of G)
        mbedtls_ecp_point mG; mbedtls_mpi mm;
        mbedtls_ecp_point_init(&mG); mbedtls_mpi_init(&mm);
        mbedtls_mpi_lset(&mm, m);
        ret = mbedtls_ecp_mul(&g_grp, &mG, &mm, &g_G,
                               mbedtls_ctr_drbg_random, &g_drbg);
        if (ret == 0) ret = ecp_add_pts(&c2_pt, &mG, &rP);
        mbedtls_ecp_point_free(&mG);
        mbedtls_mpi_free(&mm);
    }
    if (ret) goto done;

    // Compress both components to 33 bytes each
    ret = pt_compress(&c1_pt, ct->c1);
    if (ret == 0) ret = pt_compress(&c2_pt, ct->c2);

done:
    mbedtls_ecp_point_free(&rP);
    mbedtls_ecp_point_free(&c1_pt);
    mbedtls_ecp_point_free(&c2_pt);
    mbedtls_mpi_free(&r);
    return ret;
}

// Decrypt a compressed Ciphertext → 0 or 1.
// Increments g_step_decrypts so callers can count actual HE operations.
static int elgamal_decrypt(const Ciphertext* ct, int* out) {
    g_step_decrypts++;   // track how many real decryptions we perform

    mbedtls_ecp_point c1, c2, ns, pm;
    mbedtls_mpi np;
    mbedtls_ecp_point_init(&ns);
    mbedtls_ecp_point_init(&pm);
    mbedtls_mpi_init(&np);

    // Decompress both components
    int ret = pt_decompress(ct->c1, &c1); if (ret) goto done;
    ret     = pt_decompress(ct->c2, &c2); if (ret) goto done;

    // ns = -priv·c1  (computed as (N - priv)·c1 where N is the curve order)
    ret = mbedtls_mpi_sub_mpi(&np, &g_grp.N, &g_priv); if (ret) goto done;
    ret = mbedtls_ecp_mul(&g_grp, &ns, &np, &c1,
                           mbedtls_ctr_drbg_random, &g_drbg);
    if (ret) goto done;

    // pm = c2 + ns = (m·G + r·Pub) - priv·(r·G) = m·G
    ret = ecp_add_pts(&pm, &c2, &ns); if (ret) goto done;

    // m = 0 iff pm is the point at infinity
    *out = mbedtls_ecp_is_zero(&pm) ? 0 : 1;

done:
    mbedtls_ecp_point_free(&c1); mbedtls_ecp_point_free(&c2);
    mbedtls_ecp_point_free(&ns); mbedtls_ecp_point_free(&pm);
    mbedtls_mpi_free(&np);
    return ret;
}

// Homomorphic addition: out = ct_a ⊕ ct_b  (component-wise EC point addition).
// Enc(a) ⊕ Enc(b) = Enc(a+b) — this is the core HE property we exploit.
static int elgamal_add_ct(const Ciphertext* a, const Ciphertext* b,
                           Ciphertext* out) {
    mbedtls_ecp_point pa1, pa2, pb1, pb2, r1, r2;
    mbedtls_ecp_point_init(&r1); mbedtls_ecp_point_init(&r2);

    int ret = pt_decompress(a->c1, &pa1); if (ret) goto done;
    ret     = pt_decompress(a->c2, &pa2); if (ret) goto done;
    ret     = pt_decompress(b->c1, &pb1); if (ret) goto done;
    ret     = pt_decompress(b->c2, &pb2); if (ret) goto done;

    ret = ecp_add_pts(&r1, &pa1, &pb1); if (ret) goto done;  // c1_out = c1_a + c1_b
    ret = ecp_add_pts(&r2, &pa2, &pb2); if (ret) goto done;  // c2_out = c2_a + c2_b

    ret = pt_compress(&r1, out->c1); if (ret) goto done;
    ret = pt_compress(&r2, out->c2);

done:
    mbedtls_ecp_point_free(&pa1); mbedtls_ecp_point_free(&pa2);
    mbedtls_ecp_point_free(&pb1); mbedtls_ecp_point_free(&pb2);
    mbedtls_ecp_point_free(&r1);  mbedtls_ecp_point_free(&r2);
    return ret;
}


// =============================================================================
// SECTION 7 — HOMOMORPHIC OPERATORS
// =============================================================================

// sum_row — compute Enc(Σ row[i]·state[i]) for a PROGMEM enablement row.
//
// This is the core HE operation: given an encrypted state vector and a binary
// row from the enablement matrix, compute the encrypted dot product.
// The result is Enc(1) if any enabled state is active, Enc(0) otherwise.
// We then decrypt just this single scalar — the state vector stays encrypted.
static int sum_row(const std::vector<Ciphertext>& enc,
                   const int8_t* row_pm,   // PROGMEM pointer to enablement row
                   int n,
                   Ciphertext* out) {
    // Find the first state with enable=1 to initialise the accumulator.
    int first = -1, cnt = 0;
    for (int i = 0; i < n; ++i)
        if (pm_i8(row_pm, i)) { if (first < 0) first = i; ++cnt; }

    if (cnt == 0) {
        // No enabled states → result is Enc(0).
        memcpy(out, &g_zero, sizeof(Ciphertext));
        return 0;
    }

    // Start with enc[first] (plain copy — no EC operation needed).
    *out = enc[first];

    // Add remaining enabled state ciphertexts homomorphically.
    bool skip = true;
    for (int i = 0; i < n; ++i) {
        if (!pm_i8(row_pm, i)) continue;
        if (skip) { skip = false; continue; }  // already used enc[first]
        Ciphertext tmp;
        int ret = elgamal_add_ct(out, &enc[i], &tmp);
        if (ret) return ret;
        *out = tmp;
    }
    return 0;
}

// sparse_transition — apply one event's transitions to the encrypted state vector.
//
// Reads (from, to) pairs from PROGMEM and copies ciphertexts: enc_new[to] = enc[from].
// States with no incoming transition are filled with g_zero = Enc(0).
// This is equivalent to: enc_new = B · enc  where B is the sparse transition matrix.
// No decryption or EC arithmetic needed — just ciphertext copies.
static int sparse_transition(std::vector<Ciphertext>& enc,
                              const int16_t* trans_pm,  // PROGMEM (from,to) pairs
                              uint16_t pair_count,
                              int n) {
    // Build the new state vector, starting with all Enc(0).
    std::vector<Ciphertext> nxt(n, g_zero);

    // Copy enc[from] → nxt[to] for each transition pair.
    for (uint16_t p = 0; p < pair_count; ++p) {
        int from = pm_i16(trans_pm, p * 2);
        int to   = pm_i16(trans_pm, p * 2 + 1);
        nxt[to]  = enc[from];
    }

    enc = std::move(nxt);
    return 0;
}


// =============================================================================
// SECTION 8 — LOAD SUPERVISORS
// =============================================================================

// Compute the element index (not byte offset) of the first pair for event ev_gi
// in the flat transition array. Each (from, to) pair occupies 2 elements.
static int trans_offset_for_event(const SupDesc* d, int ev_gi) {
    int offset = 0;
    for (int i = 0; i < ev_gi; ++i)
        offset += (int)pm_u16(d->tcnt, i);   // sum pair counts for all earlier events
    return offset * 2;   // ×2 because each pair = 2 int16_t elements
}

// Load supervisors from a PROGMEM SupDesc array into g_sups.
// Builds bitmasks and constrained_gi lists for fast per-step lookups.
static bool load_supervisors(const SupDesc* descs, int count) {
    g_sups.clear();
    g_sups.resize(count);

    for (int i = 0; i < count; ++i) {
        Supervisor& sv = g_sups[i];
        sv.desc        = &descs[i];
        sv.cache_valid = false;

        int n = (int)pgm_read_word(&descs[i].num_states);

        sv.own_event_mask    = 0;
        sv.trans_event_mask  = 0;
        sv.constraining_mask = 0;
        sv.constrained_gi.clear();

        // Scan all events once to build bitmasks and constrained_gi.
        for (int gi = 0; gi < EVENT_COUNT; ++gi) {
            // Transition bitmask: does this event have any transition here?
            uint16_t tc = pm_u16(descs[i].tcnt, gi);
            if (tc > 0) {
                sv.own_event_mask   |= (1u << gi);
                sv.trans_event_mask |= (1u << gi);
            }

            // Constraining bitmask: does this event have any disabled state?
            // (i.e., at least one 0 in the enablement row for this event)
            bool constrains = false;
            for (int s = 0; s < n && !constrains; ++s)
                if (!pm_i8(descs[i].enable, gi * n + s)) constrains = true;

            if (constrains) {
                sv.own_event_mask    |= (1u << gi);
                sv.constraining_mask |= (1u << gi);
                sv.constrained_gi.push_back((uint8_t)gi);
            }
        }

        sv.cached_en.assign(sv.constrained_gi.size(), 1);

        // Initialise shadow from PROGMEM initial state.
        sv.shadow.resize(n);
        for (int s = 0; s < n; ++s)
            sv.shadow[s] = pm_i8(descs[i].init, s);

        // Print summary for this supervisor.
        char name_buf[16];
        strncpy_P(name_buf, (const char*)pgm_read_ptr(&descs[i].name), 15);
        name_buf[15] = 0;
        Serial.printf("[LOAD] %-10s  %3d states  %2d constraining ev  "
                      "(%u bytes enc)\n",
                      name_buf, n, (int)sv.constrained_gi.size(),
                      (unsigned)(n * sizeof(Ciphertext)));
    }
    return true;
}


// =============================================================================
// SECTION 9 — STATE INITIALISATION
// =============================================================================

// Encrypt every supervisor's initial state vector into g_sups[i].enc.
// Prints heap usage before/after to help diagnose out-of-memory errors.
// Calls yield() between individual encryptions so the RTOS watchdog does not
// fire and fragmented heap gets a chance to compact between EC operations.
static bool init_states() {
    Serial.printf("[MEM] Heap before encryption: %u bytes free\n",
                  (unsigned)heap_caps_get_free_size(MALLOC_CAP_8BIT));

    for (size_t i = 0; i < g_sups.size(); ++i) {
        Supervisor& sv = g_sups[i];
        sv.cache_valid = false;
        int n = (int)pgm_read_word(&sv.desc->num_states);
        sv.enc.resize(n);

        char name_buf[16];
        strncpy_P(name_buf, (const char*)pgm_read_ptr(&sv.desc->name), 15);
        name_buf[15] = 0;

        Serial.printf("[ENC] '%s' (%d states, %u bytes)... heap=%u\n",
                      name_buf, n, (unsigned)(n * sizeof(Ciphertext)),
                      (unsigned)heap_caps_get_free_size(MALLOC_CAP_8BIT));

        for (int s = 0; s < n; ++s) {
            yield();   // let RTOS reclaim fragmented heap between EC operations
            int8_t v     = pm_i8(sv.desc->init, s);
            sv.shadow[s] = v;   // keep shadow in sync with enc
            int ret = elgamal_encrypt((int)v, &sv.enc[s]);
            if (ret) {
                Serial.printf("[ERROR] Encrypt failed: '%s' state %d "
                              "(ret=-0x%04X, heap=%u)\n",
                              name_buf, s, -ret,
                              (unsigned)heap_caps_get_free_size(MALLOC_CAP_8BIT));
                return false;
            }
        }
        Serial.printf("[ENC] '%s' OK  heap=%u\n", name_buf,
                      (unsigned)heap_caps_get_free_size(MALLOC_CAP_8BIT));
    }

    Serial.printf("[MEM] Heap after encryption: %u bytes free\n\n",
                  (unsigned)heap_caps_get_free_size(MALLOC_CAP_8BIT));
    return true;
}

// Warm the enablement cache by HE-decrypting the initial enablement for all
// constraining events. After this, cache_valid = true for every supervisor.
static bool warm_cache() {
    for (size_t i = 0; i < g_sups.size(); ++i) {
        Supervisor& sv = g_sups[i];
        int n          = (int)pgm_read_word(&sv.desc->num_states);

        for (int li = 0; li < (int)sv.constrained_gi.size(); ++li) {
            int gi = sv.constrained_gi[li];
            Ciphertext rs;
            int ret = sum_row(sv.enc, sv.desc->enable + gi * n, n, &rs);
            if (ret) return false;
            int e;
            ret = elgamal_decrypt(&rs, &e);
            if (ret) return false;
            sv.cached_en[li] = (int8_t)e;
        }
        sv.cache_valid = true;
    }
    return true;
}


// =============================================================================
// SECTION 10 — HOMOMORPHIC STEP
// =============================================================================
//
// Process one simulation event homomorphically.
//
// For each supervisor:
//   1. If the event is not in the supervisor's alphabet → apply cached result.
//   2. If the event is owned but has no transition AND the cache is valid →
//      state is unchanged → apply cached result (no HE work).
//   3. Otherwise:
//      a. Update shadow via the same sparse transition (cleartext).
//      b. Update enc via sparse_transition (ciphertext copies, no decrypt).
//      c. For each constraining event:
//           - If shadow shows exactly 1 active state → read enablement from
//             PROGMEM directly (zero EC operations).
//           - If shadow shows 0 active states → disabled (should not happen).
//           - If shadow shows >1 active states → HE-decrypt (fallback).

static int he_step(int ev_gi, std::vector<int>& en_out) {
    en_out.assign(EVENT_COUNT, 1);   // start with all events enabled

    for (size_t i = 0; i < g_sups.size(); ++i) {
        Supervisor& sv = g_sups[i];

        // Convenience lambda: push cached enablement results into en_out.
        auto apply_cache = [&]() {
            for (int li = 0; li < (int)sv.constrained_gi.size(); ++li)
                if (!sv.cached_en[li]) en_out[sv.constrained_gi[li]] = 0;
        };

        bool ev_owned  = (ev_gi >= 0) && (sv.own_event_mask  & (1u << ev_gi));
        bool has_trans = (ev_gi >= 0) && (sv.trans_event_mask & (1u << ev_gi));

        // ── Fast path: event not owned, or owned but no state change ─────────
        if (!ev_owned || (!has_trans && sv.cache_valid)) {
            if (sv.cache_valid) apply_cache();
            continue;
        }

        sv.cache_valid = false;
        int n = (int)pgm_read_word(&sv.desc->num_states);

        // ── Apply transitions ─────────────────────────────────────────────────
        if (has_trans) {
            int      off = trans_offset_for_event(sv.desc, ev_gi);
            uint16_t pc  = pm_u16(sv.desc->tcnt, ev_gi);

            // Update shadow (cleartext) — same logic as the encrypted transition.
            std::vector<int8_t> shadow_nxt(n, 0);
            for (uint16_t p = 0; p < pc; ++p) {
                int from = pm_i16(sv.desc->trans + off, p * 2);
                int to   = pm_i16(sv.desc->trans + off, p * 2 + 1);
                shadow_nxt[to] = sv.shadow[from];
            }
            sv.shadow = std::move(shadow_nxt);

            // Update encrypted state (ciphertext copies — no decryption).
            int ret = sparse_transition(sv.enc, sv.desc->trans + off, pc, n);
            if (ret) return ret;
        }

        // ── Check enablement for each constraining event ──────────────────────
        for (int li = 0; li < (int)sv.constrained_gi.size(); ++li) {
            int gi = sv.constrained_gi[li];

            // Count active states in the shadow.
            int active_count = 0, active_state = -1;
            for (int s = 0; s < n; ++s)
                if (sv.shadow[s]) { active_count++; active_state = s; }

            int e;
#if FORCE_HE_DECRYPT
            if (false) {
#else
            if (active_count == 1) {
#endif
                // One-hot state (normal case): read enablement from PROGMEM.
                // No EC operations at all — just a table lookup in flash.
                e = (int)pm_i8(sv.desc->enable, gi * n + active_state);
            } else if (active_count == 0) {
                e = 0;   // no active state — treat as disabled (defensive)
            } else {
                // Multiple active states — must HE-decrypt the full row.
                // This should not occur in a deterministic DES supervisor.
                Ciphertext rs;
                int ret = sum_row(sv.enc, sv.desc->enable + gi * n, n, &rs);
                if (ret) return ret;
                ret = elgamal_decrypt(&rs, &e);
                if (ret) return ret;
            }

            sv.cached_en[li] = (int8_t)e;
            if (!e) en_out[gi] = 0;
        }
        sv.cache_valid = true;
    }
    return 0;
}


// =============================================================================
// SECTION 11 — ORACLE (cleartext reference)
// =============================================================================
// Runs the same simulation in pure cleartext — never timed, only used to
// verify that the HE result matches the expected (correct) result each step.

struct Oracle {
    std::vector<std::vector<int>> st;   // cleartext state per supervisor

    void init(const SupDesc* descs, int count) {
        st.resize(count);
        for (int i = 0; i < count; ++i) {
            int n = (int)pgm_read_word(&descs[i].num_states);
            st[i].resize(n);
            for (int s = 0; s < n; ++s)
                st[i][s] = pm_i8(descs[i].init, s);
        }
    }

    std::vector<int> step(int ev_gi, const SupDesc* descs, int count) {
        std::vector<int> en(EVENT_COUNT, 1);

        for (int i = 0; i < count; ++i) {
            int n = (int)pgm_read_word(&descs[i].num_states);

            // Apply transition for ev_gi (if any).
            uint16_t pc = pm_u16(descs[i].tcnt, ev_gi);
            if (pc > 0) {
                int off = 0;
                for (int gi = 0; gi < ev_gi; ++gi)
                    off += (int)pm_u16(descs[i].tcnt, gi);
                std::vector<int> nxt(n, 0);
                for (uint16_t p = 0; p < pc; ++p) {
                    int from = pm_i16(descs[i].trans, (off + p) * 2);
                    int to   = pm_i16(descs[i].trans, (off + p) * 2 + 1);
                    nxt[to]  = st[i][from];
                }
                st[i] = nxt;
            }

            // Compute enablement for all constraining events.
            if (g_sups[i].own_event_mask == 0) continue;
            for (int gi = 0; gi < EVENT_COUNT; ++gi) {
                if (!(g_sups[i].own_event_mask & (1u << gi))) continue;
                bool constrains = false;
                for (int s = 0; s < n && !constrains; ++s)
                    if (!pm_i8(descs[i].enable, gi * n + s)) constrains = true;
                if (!constrains) continue;
                int e = 0;
                for (int s = 0; s < n; ++s)
                    if (pm_i8(descs[i].enable, gi * n + s) && st[i][s]) { e = 1; break; }
                if (!e) en[gi] = 0;
            }
        }
        return en;
    }
};


// =============================================================================
// SECTION 12 — SELF-TEST
// =============================================================================
// Verifies the EC-ElGamal implementation before any benchmark runs.
// If any check fails, setup() halts with an error message.

static bool run_selftest() {
    Serial.println("============================================");
    Serial.println("  SELF-TEST: EC-ElGamal crypto verification");
    Serial.println("============================================");
    bool ok = true;

    // Test 1: Basic encrypt / decrypt correctness.
    Ciphertext ct0, ct1;
    elgamal_encrypt(0, &ct0);
    elgamal_encrypt(1, &ct1);
    int d0 = -1, d1 = -1;
    elgamal_decrypt(&ct0, &d0);
    elgamal_decrypt(&ct1, &d1);
    Serial.printf("  [1] Enc(0)->Dec=%d  Enc(1)->Dec=%d  %s\n",
                  d0, d1, (d0==0 && d1==1) ? "PASS" : "FAIL");
    if (d0 != 0 || d1 != 1) ok = false;

    // Test 2: Homomorphic add — Enc(1)+Enc(1) should decrypt to non-zero.
    Ciphertext cs11; elgamal_add_ct(&ct1, &ct1, &cs11);
    int ds11 = -1; elgamal_decrypt(&cs11, &ds11);
    Serial.printf("  [2] Enc(1)+Enc(1)->Dec=%d (expect 1)  %s\n",
                  ds11, ds11==1 ? "PASS" : "FAIL");
    if (ds11 != 1) ok = false;

    // Test 3: Homomorphic add — Enc(0)+Enc(0) should decrypt to 0.
    Ciphertext cs00; elgamal_add_ct(&ct0, &ct0, &cs00);
    int ds00 = -1; elgamal_decrypt(&cs00, &ds00);
    Serial.printf("  [3] Enc(0)+Enc(0)->Dec=%d (expect 0)  %s\n",
                  ds00, ds00==0 ? "PASS" : "FAIL");
    if (ds00 != 0) ok = false;

    // Test 4: Non-determinism — two separate Enc(1) must have different c1
    //         (same c1 would mean the random nonce r was reused — RNG broken).
    Ciphertext ct1b; elgamal_encrypt(1, &ct1b);
    bool same = (memcmp(ct1.c1, ct1b.c1, PT_LEN) == 0);
    Serial.printf("  [4] Two Enc(1) have distinct c1: %s\n",
                  !same ? "PASS" : "FAIL (RNG may be broken)");
    if (same) ok = false;

    // Test 5: Compress → decompress round-trip on the generator point G.
    uint8_t buf[PT_LEN]; size_t len = 0;
    mbedtls_ecp_point_write_binary(&g_grp, &g_G,
        MBEDTLS_ECP_PF_COMPRESSED, &len, buf, PT_LEN);
    mbedtls_ecp_point P2;
    mbedtls_ecp_point_read_binary(&g_grp, &P2, buf, PT_LEN);
    int eq = mbedtls_ecp_point_cmp(&P2, &g_G);
    mbedtls_ecp_point_free(&P2);
    Serial.printf("  [5] Compress/decompress G: %s\n",
                  eq==0 ? "PASS" : "FAIL");
    if (eq != 0) ok = false;

    Serial.printf("  Curve          : secp256k1\n");
    Serial.printf("  Ciphertext size: %u bytes (2 × %d-byte compressed points)\n",
                  (unsigned)sizeof(Ciphertext), PT_LEN);
    Serial.printf("  Self-test      : %s\n\n", ok ? "PASS" : "FAIL");
    return ok;
}


// =============================================================================
// SECTION 13 — BENCHMARK
// =============================================================================

static void print_vec(const std::vector<int>& v) {
    Serial.print("[");
    for (size_t i = 0; i < v.size(); ++i) { if (i) Serial.print(","); Serial.print(v[i]); }
    Serial.print("]");
}

static void run_benchmark(const char* label, const SupDesc* descs, int count) {
    Serial.println("============================================");
    Serial.printf("  BENCHMARK: %s\n", label);
    Serial.println("============================================");

    // Load and print supervisor summaries.
    load_supervisors(descs, count);
    Serial.println();

    // Encrypt initial states.
    if (!init_states()) {
        Serial.println("[FATAL] Encryption failed — halting.");
        while (true) delay(1000);
    }

    // Warm the enablement cache via HE decryption.
    Serial.println("Warming enablement cache...");
    if (!warm_cache()) {
        Serial.println("[FATAL] Cache warm failed — halting.");
        while (true) delay(1000);
    }
    Serial.println("Cache warm OK.\n");

    Oracle oracle;
    oracle.init(descs, count);

    // Timing accumulators (all in microseconds — micros() resolution is 1 ms).
    long total_ms = 0, min_ms = LONG_MAX, max_ms = 0;
    int  total_decrypts = 0;
    bool all_ok = true;

    for (int step = 0; step < SIM_SEQ_LEN; ++step) {
        int ev_gi = (int)pm_u16(SIM_SEQ, step);

        char ev_buf[16];
        strncpy_P(ev_buf, pm_event_name(ev_gi), 15);
        ev_buf[15] = 0;
        Serial.printf("-- Step %d | Event: %s --\n", step + 1, ev_buf);

        // Run oracle (cleartext, not timed).
        std::vector<int> oracle_en = oracle.step(ev_gi, descs, count);

        // Run HE step (timed).
        std::vector<int> he_en;
        g_step_decrypts = 0;
        long t0      = millis();
        int  ret     = he_step(ev_gi, he_en);
        long step_ms = millis() - t0;

        total_ms    += step_ms;
        total_decrypts += g_step_decrypts;
        if (step_ms < min_ms) min_ms = step_ms;
        if (step_ms > max_ms) max_ms = step_ms;

        if (ret) {
            Serial.printf("  HE ERROR -0x%04X\n", -ret);
            all_ok = false;
            continue;
        }

        Serial.print("  [Oracle] "); print_vec(oracle_en); Serial.println();
        Serial.print("  [HE]     "); print_vec(he_en);     Serial.println();
        bool ok = (he_en == oracle_en);
        if (!ok) all_ok = false;
        Serial.printf("  Time: %ld ms  |  HE decrypts: %d  |  %s\n\n",
                      step_ms, g_step_decrypts, ok ? "OK" : "FAIL");
    }

    int ns = SIM_SEQ_LEN ? SIM_SEQ_LEN : 1;
    Serial.println("--------------------------------------------");
    Serial.println("  TIMING SUMMARY");
    Serial.println("--------------------------------------------");
    Serial.printf("  Total HE time  : %ld ms  (%ld s)\n",
                  total_ms, total_ms / 1000);
    Serial.printf("  Avg  per step  : %ld ms\n", total_ms / ns);
    Serial.printf("  Min  per step  : %ld ms\n", min_ms);
    Serial.printf("  Max  per step  : %ld ms\n", max_ms);
    Serial.printf("  Total HE decrypts: %d  (shadow skipped the rest)\n",
                  total_decrypts);
    Serial.printf("  Supervisors    : %d  (ALL encrypted)\n", count);
    Serial.printf("  Result         : %s\n", all_ok ? "PASS" : "FAIL");
    Serial.println("============================================\n");

    // Free encrypted state vectors before next benchmark.
    for (auto& sv : g_sups) sv.enc.clear();
    g_sups.clear();
}


// =============================================================================
// SECTION 14 — SETUP & LOOP
// =============================================================================

void setup() {
    Serial.begin(115200);
    delay(1500);
    Serial.println("\n============================================");
    Serial.println("  ESP32 Homomorphic DES  —  UltraDES");
    Serial.println("============================================");
    Serial.printf("  EVENT_COUNT    : %d\n", EVENT_COUNT);
    Serial.printf("  SIM_SEQ_LEN    : %d\n", SIM_SEQ_LEN);
    Serial.printf("  Ciphertext     : %u bytes\n\n", (unsigned)sizeof(Ciphertext));

    // ── 1. Initialise mbedTLS ─────────────────────────────────────────────────
    mbedtls_ecp_group_init(&g_grp);
    mbedtls_ecp_point_init(&g_G);
    mbedtls_ecp_point_init(&g_pub);
    mbedtls_mpi_init(&g_priv);
    mbedtls_mpi_init(&g_one);
    mbedtls_ctr_drbg_init(&g_drbg);
    mbedtls_entropy_init(&g_entropy);
    mbedtls_mpi_lset(&g_one, 1);

    // Seed the RNG from the ESP32 hardware entropy source.
    const char* pers = "esp32_he_des";
    mbedtls_ctr_drbg_seed(&g_drbg, mbedtls_entropy_func, &g_entropy,
                           (const uint8_t*)pers, strlen(pers));

    // Load secp256k1 curve and generate a fresh keypair.
    mbedtls_ecp_group_load(&g_grp, CURVE);
    mbedtls_ecp_copy(&g_G, &g_grp.G);
    mbedtls_ecp_gen_keypair(&g_grp, &g_priv, &g_pub,
                             mbedtls_ctr_drbg_random, &g_drbg);

    // Pre-encrypt Enc(0) for use as the sparse-transition fill value.
    elgamal_encrypt(0, &g_zero);

    // ── 2. Measure EC operation timing ────────────────────────────────────────
    {
        mbedtls_ecp_point P, Q, R; mbedtls_mpi k;
        mbedtls_ecp_point_init(&P); mbedtls_ecp_point_init(&Q);
        mbedtls_ecp_point_init(&R); mbedtls_mpi_init(&k);
        mbedtls_ecp_copy(&P, &g_G); mbedtls_ecp_copy(&Q, &g_G);
        mbedtls_mpi_lset(&k, 1);
        long t0 = millis();
        for (int i = 0; i < 5; ++i)
            mbedtls_ecp_muladd(&g_grp, &R, &k, &P, &k, &Q);
        g_muladd_ms = (millis() - t0) / 5;
        t0 = millis();
        for (int i = 0; i < 5; ++i)
            mbedtls_ecp_mul(&g_grp, &R, &k, &g_G,
                             mbedtls_ctr_drbg_random, &g_drbg);
        g_scalarmul_ms = (millis() - t0) / 5;
        mbedtls_ecp_point_free(&P); mbedtls_ecp_point_free(&Q);
        mbedtls_ecp_point_free(&R); mbedtls_mpi_free(&k);
        Serial.printf("[Crypto] muladd=%ld ms  scalar_mul=%ld ms\n\n",
                      g_muladd_ms, g_scalarmul_ms);
    }

    // ── 3. Self-test — must pass before any benchmark ─────────────────────────
    g_step_decrypts = 0;   // clear self-test decrypt counts before benchmarks
    if (!run_selftest()) {
        Serial.println("Self-test FAILED — halting. Check mbedTLS init.");
        while (true) delay(1000);
    }

    // ── 4. Monolithic benchmark (skipped if notebook omitted it) ─────────────
#if HAS_MONO
    run_benchmark("MONOLITHIC", &MONO_SUP, 1);
#else
    Serial.println("[SKIP] Monolithic supervisor not included "
                   "(exceeded flash budget in notebook).\n");
#endif

    // ── 5. Local modular benchmark ────────────────────────────────────────────
    run_benchmark("LOCAL MODULAR", LMOD_SUPS, LMOD_COUNT);

    // ── 6. Local modular REDUCED benchmark ───────────────────────────────────
    run_benchmark("LOCAL MODULAR REDUCED", LMOD_RED_SUPS, LMOD_RED_COUNT);

    // ── 7. Cleanup mbedTLS resources ──────────────────────────────────────────
    mbedtls_ecp_group_free(&g_grp);
    mbedtls_ecp_point_free(&g_G);   mbedtls_ecp_point_free(&g_pub);
    mbedtls_mpi_free(&g_priv);      mbedtls_mpi_free(&g_one);
    mbedtls_ctr_drbg_free(&g_drbg); mbedtls_entropy_free(&g_entropy);

    Serial.println("All benchmarks complete.");
}

void loop() {
    // Nothing to do — all work happens once in setup().
    delay(10000);
}
