// supervisor_data_extended_small_factory.h
// Auto-generated by the UltraDES notebook — DO NOT EDIT BY HAND.
// Re-run Cell 7 to regenerate.
//
// Problem   : extended_small_factory
// Events    : ['a1', 'a2', 'a3', 'b1', 'b2', 'b3']
// Sim seq   : ['a1', 'b1', 'a2', 'b2', 'a3', 'b3']
// Monolithic: INCLUDED

#pragma once
#include <stdint.h>
// pgmspace.h is provided automatically by the ESP32 Arduino core.

// Total number of events across all plants and specs.
#define EVENT_COUNT 6

// Number of steps in the simulation sequence.
#define SIM_SEQ_LEN 6

// Event names in global index order (index = position in EVENT_NAMES[]).
static const char EV_0[] PROGMEM = "a1";
static const char EV_1[] PROGMEM = "a2";
static const char EV_2[] PROGMEM = "a3";
static const char EV_3[] PROGMEM = "b1";
static const char EV_4[] PROGMEM = "b2";
static const char EV_5[] PROGMEM = "b3";
static const char* const EVENT_NAMES[] PROGMEM = {
    EV_0, EV_1, EV_2, EV_3, EV_4, EV_5
};

// Simulation sequence: each entry is a global event index into EVENT_NAMES[].
static const uint16_t SIM_SEQ[] PROGMEM = {
    0, 3, 1, 4, 2, 5
};


// Descriptor struct — one instance per supervisor.
// All pointer fields point into PROGMEM arrays defined below.
struct SupDesc {
    const char*      name;       // supervisor label (PROGMEM string)
    uint16_t         num_states; // total number of states
    const int8_t*    init;       // one-hot initial state vector [num_states]
    const int8_t*    enable;     // enablement matrix [EVENT_COUNT * num_states]
    const uint16_t*  tcnt;       // transition pair counts per event [EVENT_COUNT]
    const int16_t*   trans;      // flat (from,to) transition pairs
};

// ── Local modular supervisors (2 total) ──────────────────────────────────
#define LMOD_COUNT 2

// S0  —  6 states, 8 transitions
static const int8_t lm0_init[] PROGMEM = {
    1, 0, 0, 0, 0, 0
};

static const int8_t lm0_enable[] PROGMEM = {
    1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
    1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1
};

static const uint16_t lm0_tcnt[] PROGMEM = {
    2, 1, 0, 2, 3, 0
};

static const int16_t lm0_trans[] PROGMEM = {
    0, 2, 3, 1, 5, 3, 2, 5, 1, 4, 3, 0, 1, 2, 4, 5
};

static const char LMOD_0_NAME[] PROGMEM = "S0";

// S1  —  6 states, 8 transitions
static const int8_t lm1_init[] PROGMEM = {
    1, 0, 0, 0, 0, 0
};

static const int8_t lm1_enable[] PROGMEM = {
    1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
    1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0
};

static const uint16_t lm1_tcnt[] PROGMEM = {
    0, 2, 1, 0, 2, 3
};

static const int16_t lm1_trans[] PROGMEM = {
    0, 2, 3, 1, 5, 3, 2, 5, 1, 4, 3, 0, 1, 2, 4, 5
};

static const char LMOD_1_NAME[] PROGMEM = "S1";

static const SupDesc LMOD_SUPS[] = {
    // S0: 6 states
    { LMOD_0_NAME, 6, lm0_init, lm0_enable, lm0_tcnt, lm0_trans },
    // S1: 6 states
    { LMOD_1_NAME, 6, lm1_init, lm1_enable, lm1_tcnt, lm1_trans },
};

// ── Local modular reduced supervisors (2 total) ──────────────────────
#define LMOD_RED_COUNT 2

// S0_red  —  2 states (+4), 5 transitions (+3)
static const int8_t lmr0_init[] PROGMEM = {
    1, 0
};

static const int8_t lmr0_enable[] PROGMEM = {
    1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1
};

static const uint16_t lmr0_tcnt[] PROGMEM = {
    1, 1, 0, 1, 2, 0
};

static const int16_t lmr0_trans[] PROGMEM = {
    0, 0, 1, 0, 0, 1, 0, 0, 1, 1
};

static const char LMOD_RED_0_NAME[] PROGMEM = "S0_red";

// S1_red  —  2 states (+4), 5 transitions (+3)
static const int8_t lmr1_init[] PROGMEM = {
    1, 0
};

static const int8_t lmr1_enable[] PROGMEM = {
    1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1
};

static const uint16_t lmr1_tcnt[] PROGMEM = {
    0, 1, 1, 0, 1, 2
};

static const int16_t lmr1_trans[] PROGMEM = {
    0, 0, 1, 0, 0, 1, 0, 0, 1, 1
};

static const char LMOD_RED_1_NAME[] PROGMEM = "S1_red";

static const SupDesc LMOD_RED_SUPS[] = {
    // S0_red: 2 states
    { LMOD_RED_0_NAME, 2, lmr0_init, lmr0_enable, lmr0_tcnt, lmr0_trans },
    // S1_red: 2 states
    { LMOD_RED_1_NAME, 2, lmr1_init, lmr1_enable, lmr1_tcnt, lmr1_trans },
};

// ── Monolithic supervisor — 18 states ─────────────────────────
static const int8_t mono_init[] PROGMEM = {
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

static const int8_t mono_enable[] PROGMEM = {
    1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
    0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
    1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
    0, 1, 1, 1, 1, 0, 0, 0
};

static const uint16_t mono_tcnt[] PROGMEM = {
    6, 2, 3, 6, 6, 9
};

static const int16_t mono_trans[] PROGMEM = {
    0, 5, 9, 2, 7, 1, 12, 4, 15, 6, 11, 3, 16, 9, 13, 7,
    6, 3, 17, 13, 15, 11, 5, 16, 2, 10, 6, 17, 3, 13, 1, 8,
    4, 14, 9, 15, 2, 6, 7, 12, 1, 4, 8, 14, 10, 17, 3, 5,
    13, 16, 7, 9, 1, 2, 4, 6, 14, 17, 8, 10, 12, 15, 11, 0
};

static const char MONO_NAME[] PROGMEM = "Monolithic";
#define MONO_NUM_STATES 18
static const SupDesc MONO_SUP = {
    MONO_NAME, 18, mono_init, mono_enable, mono_tcnt, mono_trans
};
#define HAS_MONO 1

