// supervisor_data_small_factory.h
// Auto-generated by the UltraDES notebook — DO NOT EDIT BY HAND.
// Re-run Cell 7 to regenerate.
//
// Problem   : small_factory
// Events    : ['e1', 'e2', 'e3', 'e4']
// Sim seq   : ['e1', 'e2', 'e3', 'e4']
// Monolithic: INCLUDED

#pragma once
#include <stdint.h>
// pgmspace.h is provided automatically by the ESP32 Arduino core.

// Total number of events across all plants and specs.
#define EVENT_COUNT 4

// Number of steps in the simulation sequence.
#define SIM_SEQ_LEN 4

// Event names in global index order (index = position in EVENT_NAMES[]).
static const char EV_0[] PROGMEM = "e1";
static const char EV_1[] PROGMEM = "e2";
static const char EV_2[] PROGMEM = "e3";
static const char EV_3[] PROGMEM = "e4";
static const char* const EVENT_NAMES[] PROGMEM = {
    EV_0, EV_1, EV_2, EV_3
};

// Simulation sequence: each entry is a global event index into EVENT_NAMES[].
static const uint16_t SIM_SEQ[] PROGMEM = {
    0, 1, 2, 3
};


// Descriptor struct — one instance per supervisor.
// All pointer fields point into PROGMEM arrays defined below.
struct SupDesc {
    const char*      name;       // supervisor label (PROGMEM string)
    uint16_t         num_states; // total number of states
    const int8_t*    init;       // one-hot initial state vector [num_states]
    const int8_t*    enable;     // enablement matrix [EVENT_COUNT * num_states]
    const uint16_t*  tcnt;       // transition pair counts per event [EVENT_COUNT]
    const int16_t*   trans;      // flat (from,to) transition pairs
};

// ── Local modular supervisors (1 total) ──────────────────────────────────
#define LMOD_COUNT 1

// S0  —  6 states, 8 transitions
static const int8_t lm0_init[] PROGMEM = {
    1, 0, 0, 0, 0, 0
};

static const int8_t lm0_enable[] PROGMEM = {
    1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
    0, 1, 1, 0
};

static const uint16_t lm0_tcnt[] PROGMEM = {
    2, 2, 1, 3
};

static const int16_t lm0_trans[] PROGMEM = {
    0, 2, 3, 1, 2, 5, 1, 4, 5, 3, 3, 0, 1, 2, 4, 5
};

static const char LMOD_0_NAME[] PROGMEM = "S0";

static const SupDesc LMOD_SUPS[] = {
    // S0: 6 states
    { LMOD_0_NAME, 6, lm0_init, lm0_enable, lm0_tcnt, lm0_trans },
};

// ── Local modular reduced supervisors (1 total) ──────────────────────
#define LMOD_RED_COUNT 1

// S0_red  —  2 states (+4), 5 transitions (+3)
static const int8_t lmr0_init[] PROGMEM = {
    1, 0
};

static const int8_t lmr0_enable[] PROGMEM = {
    1, 0, 1, 0, 0, 1, 1, 1
};

static const uint16_t lmr0_tcnt[] PROGMEM = {
    1, 1, 1, 2
};

static const int16_t lmr0_trans[] PROGMEM = {
    0, 0, 0, 1, 1, 0, 0, 0, 1, 1
};

static const char LMOD_RED_0_NAME[] PROGMEM = "S0_red";

static const SupDesc LMOD_RED_SUPS[] = {
    // S0_red: 2 states
    { LMOD_RED_0_NAME, 2, lmr0_init, lmr0_enable, lmr0_tcnt, lmr0_trans },
};

// ── Monolithic supervisor — 6 states ─────────────────────────
static const int8_t mono_init[] PROGMEM = {
    1, 0, 0, 0, 0, 0
};

static const int8_t mono_enable[] PROGMEM = {
    1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
    0, 1, 1, 0
};

static const uint16_t mono_tcnt[] PROGMEM = {
    2, 2, 1, 3
};

static const int16_t mono_trans[] PROGMEM = {
    0, 2, 3, 1, 2, 5, 1, 4, 5, 3, 3, 0, 1, 2, 4, 5
};

static const char MONO_NAME[] PROGMEM = "Monolithic";
#define MONO_NUM_STATES 6
static const SupDesc MONO_SUP = {
    MONO_NAME, 6, mono_init, mono_enable, mono_tcnt, mono_trans
};
#define HAS_MONO 1

